services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: projetdb
      MYSQL_USER: projetuser
      MYSQL_PASSWORD: projetpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./workshop_client.sql:/docker-entrypoint-initdb.d/workshop_client.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend      # contexte de build : backend
      dockerfile: backend.dockerfile  # Dockerfile à l'intérieur de ./backend
    container_name: nest_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app        # hot reload
      - /app/node_modules
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: projetuser
      DATABASE_PASSWORD: projetpass
      DATABASE_NAME: projetdb
      DATABASE_URL: mysql://root:rootpassword@mysql:3306/projetdb
    depends_on:
      mysql:
        condition: service_healthy
        restart: true

  frontend:
    build:
      context: ./workshop     # contexte de build : workshop
      dockerfile: frontend.dockerfile
    container_name: react_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./workshop:/app       # hot reload
      - /app/node_modules
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
